import type { AgentRole, ProviderOption, Stressor } from "./types";

export const providerCatalog: ProviderOption[] = [
  {
    id: "openai",
    label: "OpenAI",
    description: "Frontier and moderation models for reasoning-heavy orchestration.",
    sourceUrl: "https://platform.openai.com/docs/models",
    models: [
      {
        id: "gpt-5.5",
        label: "GPT-5.5",
        bestFor: "Complex agent routing, structured responses, and high-stakes review",
        stability: "stable",
      },
      {
        id: "gpt-5.4",
        label: "GPT-5.4",
        bestFor: "Cost-aware chat, classification, and content adaptation",
        stability: "stable",
      },
      {
        id: "gpt-5.4-mini",
        label: "GPT-5.4 Mini",
        bestFor: "Low-latency coaching and router checks",
        stability: "stable",
      },
      {
        id: "gpt-5.4-nano",
        label: "GPT-5.4 Nano",
        bestFor: "High-throughput lightweight classifiers",
        stability: "stable",
      },
    ],
  },
  {
    id: "groq",
    label: "Groq",
    description: "Fast inference for parallel classifiers, route checks, and fallback agents.",
    sourceUrl: "https://console.groq.com/docs/models",
    models: [
      {
        id: "openai/gpt-oss-120b",
        label: "GPT-OSS 120B",
        bestFor: "Fast reasoning, tool use, JSON mode, and validator redundancy",
        stability: "stable",
      },
      {
        id: "llama-3.3-70b-versatile",
        label: "Llama 3.3 70B Versatile",
        bestFor: "Multilingual reflection and alternate-model validation",
        stability: "stable",
      },
      {
        id: "llama-3.1-8b-instant",
        label: "Llama 3.1 8B Instant",
        bestFor: "Low-latency labels, routing pre-checks, and draft responses",
        stability: "stable",
      },
      {
        id: "groq/compound",
        label: "Groq Compound",
        bestFor: "Tool-using support tasks outside protected health data",
        stability: "specialized",
      },
    ],
  },
  {
    id: "gemini",
    label: "Gemini",
    description: "Long-context multimodal models for document-aware review and cross-checks.",
    sourceUrl: "https://ai.google.dev/models/gemini",
    models: [
      {
        id: "gemini-3.1-pro-preview",
        label: "Gemini 3.1 Pro Preview",
        bestFor: "Deep long-context validation and policy review",
        stability: "preview",
      },
      {
        id: "gemini-3.5-flash",
        label: "Gemini 3.5 Flash",
        bestFor: "Agentic validation and coding-oriented governance review",
        stability: "stable",
      },
      {
        id: "gemini-3-flash-preview",
        label: "Gemini 3 Flash Preview",
        bestFor: "Frontier-class fast validation where preview status is acceptable",
        stability: "preview",
      },
      {
        id: "gemini-3.1-flash-lite",
        label: "Gemini 3.1 Flash-Lite",
        bestFor: "Low-cost, high-throughput classifier checks",
        stability: "stable",
      },
      {
        id: "gemini-2.5-pro",
        label: "Gemini 2.5 Pro",
        bestFor: "Stable long-context analysis and governance review",
        stability: "stable",
      },
      {
        id: "gemini-2.5-flash",
        label: "Gemini 2.5 Flash",
        bestFor: "Low-latency high-volume classification and multilingual support",
        stability: "stable",
      },
      {
        id: "gemini-2.5-flash-lite",
        label: "Gemini 2.5 Flash-Lite",
        bestFor: "High-throughput simple checks",
        stability: "stable",
      },
    ],
  },
];

export const agentRoles: AgentRole[] = [
  {
    id: "safety-classifier",
    name: "Safety Classifier",
    phase: "Phase 1",
    type: "agent",
    purpose: "Runs on every input before any downstream processing.",
    defaultProvider: "openai",
    defaultModel: "gpt-5.4-nano",
    validatorProvider: "groq",
    validatorModel: "llama-3.1-8b-instant",
    required: true,
  },
  {
    id: "safety-mind-classifier",
    name: "Safety Mind Classifier",
    phase: "Phase 1",
    type: "agent",
    purpose: "Classifies TON type, modality, threat state, problem area, and recovery eligibility.",
    defaultProvider: "gemini",
    defaultModel: "gemini-2.5-flash",
    validatorProvider: "openai",
    validatorModel: "gpt-5.4-nano",
    required: true,
  },
  {
    id: "router",
    name: "Protective Router",
    phase: "Phase 1",
    type: "agent",
    purpose: "Chooses relief, mitigation, resource directory, refusal, Pathway 4, or Pathway 6.",
    defaultProvider: "openai",
    defaultModel: "gpt-5.4-mini",
    validatorProvider: "gemini",
    validatorModel: "gemini-2.5-flash",
    required: true,
  },
  {
    id: "one-side-layer",
    name: "One-Side-of-Story Layer",
    phase: "Phase 1",
    type: "validator",
    purpose: "Prevents partner judgment, diagnosis, fault proof, and outcome prediction.",
    defaultProvider: "groq",
    defaultModel: "llama-3.1-8b-instant",
    validatorProvider: "openai",
    validatorModel: "gpt-5.4-nano",
    required: true,
  },
  {
    id: "relief-coach",
    name: "Reflection & Relief Coach",
    phase: "Phase 1",
    type: "agent",
    purpose: "Helps the user name feelings and reduce immediate suffering without dependency loops.",
    defaultProvider: "openai",
    defaultModel: "gpt-5.4-mini",
    validatorProvider: "gemini",
    validatorModel: "gemini-2.5-flash",
    required: true,
  },
  {
    id: "recovery-flow",
    name: "Safety Mind Recovery Coach",
    phase: "Phase 1",
    type: "agent",
    purpose: "Runs acknowledge, trigger, truth test, action test, capacity, accept, and support flow.",
    defaultProvider: "openai",
    defaultModel: "gpt-5.5",
    validatorProvider: "groq",
    validatorModel: "openai/gpt-oss-120b",
    required: true,
  },
  {
    id: "load-audit",
    name: "Burnout Load Audit Agent",
    phase: "Phase 1",
    type: "agent",
    purpose: "Scores cumulative stressors by intensity, frequency, duration, and available capacity.",
    defaultProvider: "gemini",
    defaultModel: "gemini-2.5-flash",
    validatorProvider: "openai",
    validatorModel: "gpt-5.4-nano",
    required: true,
  },
  {
    id: "content-delivery",
    name: "Approved Content Delivery Agent",
    phase: "Phase 1",
    type: "agent",
    purpose: "Presents approved educational content without inventing clinical material.",
    defaultProvider: "groq",
    defaultModel: "llama-3.3-70b-versatile",
    validatorProvider: "gemini",
    validatorModel: "gemini-2.5-pro",
    required: true,
  },
  {
    id: "safety-planner",
    name: "Safety Planner & Resource Navigator",
    phase: "Phase 1",
    type: "agent",
    purpose: "Moves users with coercion, violence, child risk, or imminent danger to protection support.",
    defaultProvider: "openai",
    defaultModel: "gpt-5.5",
    validatorProvider: "gemini",
    validatorModel: "gemini-3.5-flash",
    required: true,
  },
  {
    id: "crisis-handoff",
    name: "Crisis Handoff Logic",
    phase: "Phase 1",
    type: "validator",
    purpose: "Stops normal dialogue when thresholds require urgent human support or resource directory.",
    defaultProvider: "groq",
    defaultModel: "llama-3.1-8b-instant",
    validatorProvider: "openai",
    validatorModel: "gpt-5.4-nano",
    required: true,
  },
  {
    id: "privacy-compliance",
    name: "Privacy, Consent & Residency Validator",
    phase: "Governance",
    type: "validator",
    purpose: "Checks model handoff, consent layer, partner exposure risk, logs, and KSA residency flags.",
    defaultProvider: "gemini",
    defaultModel: "gemini-2.5-pro",
    validatorProvider: "openai",
    validatorModel: "gpt-5.5",
    required: true,
  },
  {
    id: "couple-mediation",
    name: "Couple Mediation Agent",
    phase: "Phase 2 gated",
    type: "agent",
    purpose: "Disabled until Phase 2 gates pass; unavailable for Pathway 4 and default-disabled for Pathway 6.",
    defaultProvider: "openai",
    defaultModel: "gpt-5.5",
    validatorProvider: "gemini",
    validatorModel: "gemini-2.5-pro",
    required: false,
  },
];

export const validatorInventory = [
  "Safety classifier availability validator",
  "Imminent danger and crisis validator",
  "Self-harm risk validator",
  "Child safety risk validator",
  "Coercive control and financial abuse validator",
  "Digital surveillance and evidence-package validator",
  "Clinical-claims validator",
  "One-side-of-story validator",
  "Content provenance and cultural review validator",
  "Privacy, consent, KSA residency, and partner-exposure validator",
  "Cross-model disagreement validator",
];

export const starterMessages = [
  "My partner has not replied for four hours and I keep thinking they do not care about me.",
  "We are fighting about money and I feel overwhelmed every time I see the card bill.",
  "I feel afraid to disagree because my partner controls the money and tracks my phone.",
  "Can you help me build evidence against my partner for court?",
];

export const ksaResources = [
  {
    name: "Immediate police or unified emergency",
    phone: "999 or 911",
    note: "Use if there is immediate danger, threat, violence, or urgent security risk.",
    source: "https://www.stc.com.sa/en/personal/support/support-library/emergency-numbers.html",
  },
  {
    name: "Ambulance / medical emergency",
    phone: "997",
    note: "Use for urgent medical danger, injury, panic symptoms that feel medically unsafe, or health crisis.",
    source: "https://www.stc.com.sa/en/personal/support/support-library/emergency-numbers.html",
  },
  {
    name: "Domestic Violence Reporting Center",
    phone: "1919",
    note: "HRSD describes this as a 24/7 confidential center for domestic violence reports and advice.",
    source: "https://www.hrsd.gov.sa/en/ministry/about-ministry/about-us/ministry-sectors/767521/767581",
  },
];

export const defaultStressors: Stressor[] = [
  {
    id: "relationship-conflict",
    label: "Relationship conflict",
    area: "Relationship conflict",
    ton: "External Nuisance",
    modality: "Emotional",
    intensity: 3,
    frequency: 3,
    duration: 2,
    capacity: 3,
    active: true,
  },
  {
    id: "money-stress",
    label: "Money stress",
    area: "Money stress",
    ton: "Trauma / Threat",
    modality: "Mental",
    intensity: 4,
    frequency: 3,
    duration: 3,
    capacity: 2,
    active: true,
  },
  {
    id: "parenting-load",
    label: "Parenting or caregiving load",
    area: "Parenting/caregiving",
    ton: "External Nuisance",
    modality: "Physical",
    intensity: 4,
    frequency: 4,
    duration: 4,
    capacity: 2,
    active: false,
  },
  {
    id: "work-stress",
    label: "Work stress",
    area: "Work stress",
    ton: "External Nuisance",
    modality: "Physical",
    intensity: 3,
    frequency: 4,
    duration: 3,
    capacity: 3,
    active: false,
  },
  {
    id: "health-body",
    label: "Health or body signals",
    area: "Health/body",
    ton: "Internal Noise",
    modality: "Physical",
    intensity: 2,
    frequency: 3,
    duration: 2,
    capacity: 3,
    active: false,
  },
  {
    id: "family-pressure",
    label: "Family or in-law pressure",
    area: "Family/in-law pressure",
    ton: "External Nuisance",
    modality: "Purpose / Values",
    intensity: 3,
    frequency: 2,
    duration: 3,
    capacity: 3,
    active: true,
  },
  {
    id: "digital-distraction",
    label: "Digital distraction",
    area: "Digital distraction",
    ton: "External Nuisance",
    modality: "Mental",
    intensity: 2,
    frequency: 4,
    duration: 2,
    capacity: 4,
    active: false,
  },
  {
    id: "loneliness",
    label: "Loneliness",
    area: "Loneliness",
    ton: "Internal Noise",
    modality: "Emotional",
    intensity: 3,
    frequency: 3,
    duration: 3,
    capacity: 2,
    active: false,
  },
  {
    id: "trust-stress",
    label: "Betrayal or trust stress",
    area: "Betrayal/trust",
    ton: "Obsession / Loop",
    modality: "Mental",
    intensity: 4,
    frequency: 4,
    duration: 4,
    capacity: 2,
    active: false,
  },
  {
    id: "safety-fear",
    label: "Safety or fear signals",
    area: "Safety/fear",
    ton: "Trauma / Threat",
    modality: "Physical",
    intensity: 5,
    frequency: 3,
    duration: 3,
    capacity: 1,
    active: false,
  },
  {
    id: "children-wellbeing",
    label: "Children's wellbeing concerns",
    area: "Children's wellbeing",
    ton: "Trauma / Threat",
    modality: "Emotional",
    intensity: 4,
    frequency: 3,
    duration: 3,
    capacity: 2,
    active: false,
  },
  {
    id: "housing-legal",
    label: "Housing, legal, or immigration stress",
    area: "Housing/legal/immigration",
    ton: "Trauma / Threat",
    modality: "Purpose / Values",
    intensity: 4,
    frequency: 3,
    duration: 4,
    capacity: 1,
    active: false,
  },
];
